name: hiking

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x] 

    steps:
      - name: Git clone my repo
        uses : actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
        
      - name: Install node/modules
        run : yarn install

      - name: List files
        run : ls -la
        
      - name: Build the project
        run : yarn build

      - name: Send all materials
        uses: appleboy/scp-action@master
        with:
          host: '77.246.247.250'
          username: 'root'
          password: 'lcAIp69zjTcK!'
          port: '22'
          source: ".nuxt,assets,layouts,static,package.json,nuxt.config.js"
          target: '/var/www/hiking_frontend'

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: '77.246.247.250'
          username: 'root'
          password: 'lcAIp69zjTcK!'
          port: "22"
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/hiking_frontend
            yarn install
            pm2 start
